routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\Authcontroller;
use App\Http\Controllers\BookController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CountryController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\RolePermissionController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\UserPermissionController;
use App\Http\Middleware\checkAge;
use App\Mail\WelComeEmail;
use App\Models\Category;
use GuzzleHttp\Middleware;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/* Route::get('/', function () {
    return view('welcome');
}); */
//admin + user (web) both > login + logout 
//admin >> categories + countries 
//user > books 
//we need to add guard as parameter , dynamic attribute 

Route::prefix('cms/')->middleware('guest:admin,user')->group(function(){
  //  Route::view('login','cms.auth.login')->name('cms.login');
  Route::get('{guard}/login',[Authcontroller::class,'showlogin'])->name('cms.login');
  Route::post('login',[Authcontroller::class,'login']);
});

Route::prefix('cms/admin')->middleware('auth:admin')->group(function (){
  /*Note: route resbonsible to show >> index */
  Route::resource('admins', AdminController::class);
  Route::resource('roles', RoleController::class);
  Route::resource('permissions', PermissionController::class);
  
  Route::resource('permissions/role', RolePermissionController::class);
  Route::resource('permissions/user-permissions', UserPermissionController::class);
  Route::resource('users', UserController::class);
  

});

Route::prefix('cms/admin')->middleware('auth:admin,user')->group(function () {
  Route::view('/', 'cms.empty');
  Route::resource('books', BookController::class);
  Route::resource('categories', CategoryController::class);
  Route::resource('countries', CountryController::class);
  Route::get('change-password', [Authcontroller::class, 'showChangePassword'])->name('cms.changePassword');
  Route::post('change-password', [Authcontroller::class, 'changePassword']);
  Route::get('logout', [Authcontroller::class, 'logout'])->name('cms.logout');
});


Route::prefix('mail')->group(function(){
      Route::get('welcome',function(){
        return new WelComeEmail(); //markdown blade 
      });
});




//First way >> installation method of middleware 
// Route::get('news',function(){
//    return 'welcome to news page ';
// })->middleware('age:22',);


//second way 
// Route::get('news',function(){
  
//   /// return 'welcome to news page ';
//    return response()->json(['status'=>'success','active'=>true]);
//  })->middleware(checkAge::class);

 //third way 
//  Route::middleware('age:22',)->get('news',function(){
//     return 'welcome to news page ';
//  });

//forth way 
// Route::middleware('age:22',)->group(function(){
//   Route::get('news',function(){
//    return 'welcome to news page';
//      })->withoutMiddleware('age');
// });

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Hash;
use Laravel\Passport\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasFactory, Notifiable, HasRoles, HasApiTokens;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];



    /**
     * Find the user instance for the given username.
     *
     * @param  string  $username
     * @return \App\Models\User
     */
    public function findForPassport($username)
    {
        return $this->where('email', $username)->first();
    }


    /**
     * Validate the password of the user for the Passport password grant.
     *
     * @param  string  $password
     * @return bool
     */
    public function validateForPassportPasswordGrant($password)
    {
        return Hash::check($password, $this->password);
    }
}

    

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Spatie\Permission\Models\Role;
use Symfony\Component\HttpFoundation\Request as HttpFoundationRequest;
use Symfony\Component\HttpFoundation\Response;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

     //Role created based on spesifc guard and the user take role that have permission from the same guard
     //
    public function index()
    {
        //
        // $roles = Role::all();      
        //to get number of permissions for the role 
        $roles = Role::withCount('permissions')->get();
        return response()->view('cms.roles.index',['roles'=>$roles]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return response()->view('cms.roles.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $validator = Validator($request->all(),[
              'name'=>'required|string|min:3|max:40',
              'guard'=> 'required|string|in:user,admin',
        ]);
        if(!$validator->fails()){
                $role = new Role();
                $role->name =$request->get('name');
                $role->guard_name =$request->get('name');
                $isSaved =$role->save();
                 return response()->json(['message'=> $isSaved ? 'Saved successfully': 'Failed to save'],$isSaved ? Response::HTTP_CREATED : Response::HTTP_BAD_REQUEST);
        }else{
                return response()->json(['message'=> $validator->getMessageBag()->first(),Response::HTTP_BAD_REQUEST]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Role $role)
    {
        //
        // $isDeleted = $role->delete();
        //  return response()->json(['message'=>$isDeleted ? 'Deleted successfully' : 'Failed to delete role'], 
        //  $isDeleted ? Response::HTTP_OK : Response::HTTP_BAD_REQUEST);

        $deleted = $role->delete();
        if ($deleted) {
            return response()->json(['title' => 'Deleted successfully', 'icon' => 'success']); //key>>string""  value>>int object double boolean array of any type or array of json  //begin with objects or array
        } else {
            return response()->json(['title' => 'Deleted failed', 'icon' => 'warining']);
        }
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Mail\WelComeEmail;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Mail;
use Symfony\Component\HttpFoundation\Response;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $users = User::all();
        // $users = User::withCount('permission')->get();
        return response()->view('cms.users.index', ['users' => $users]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return response()->view('cms.users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $validator = Validator($request->all(), [
            'name' => 'required|string|min:3|max:40',
            'email' => 'required|email|string|unique:users,email',
        ]);

        if (!$validator->fails()) {
            $user = new User();
            $user->name = $request->get('name');
            $user->email = $request->get('email');
            $user->password = Hash::make(12345);
            $isSaved = $user->save();
            if ($isSaved) Mail::to($user->email)->send(new WelcomeEmail());
            return response()->json(['message' => $isSaved ? 'User saved successfully' : 'Failed to save user'], 
            $isSaved ? Response::HTTP_CREATED : Response::HTTP_BAD_REQUEST);
        } else {
            return response()->json(['message' => $validator->getMessageBag()->first()], Response::HTTP_BAD_REQUEST);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        //
        return response()->view('cms.users.edit', ['user' => $user]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        //
        $validator = Validator($request->all(), [
            'name' => 'required|string|min:3|max:40',
            'email' => 'required|email|string|unique:users,email,' . $user->id,
        ]);
        if (!$validator->fails()) {


            $user->name = $request->get('name');
            $user->email = $request->get('email');
            $user->password = Hash::make(12345);
            $isSaved = $user->save();
            return response()->json(['message' => $isSaved ? 'User saved successfully ' : 'Failed to save User'], $isSaved ? Response::HTTP_CREATED : Response::HTTP_BAD_REQUEST);
        } else {
            return response()->json(['message' => $validator->getMessageBag()->first()], Response::HTTP_BAD_REQUEST);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        //

        $isDeleted = $user->delete();
        if ($isDeleted) {
            return response()->json(['title' => 'Deleted successfully', 'icon' => 'success']); //key>>string""  value>>int object double boolean array of any type or array of json  //begin with objects or array
        } else {
            return response()->json(['title' => 'Deleted failed', 'icon' => 'error']);
        }
    }
}

resources/views/cms/users/create.blade.php
@extends('cms.parent')

@section('title','DEMO')
@section('page-large-name','Library System')
@section('page-small-name','Admin')

@section('styles')
<!-- Select2 -->
<link rel="stylesheet" href="{{asset('cms/plugins/select2/css/select2.min.css')}}">
<link rel="stylesheet" href="{{asset('cms/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css')}}">
@endsection

@section('content')
    <!-- Main content -->
    <section class="content">
		<div class="container-fluid">
		  <div class="row">
			<!-- left column -->
			<div class="col-md-12">
			  <!-- general form elements -->
			  <div class="card card-primary">
				<div class="card-header">
				  <h3 class="card-title">Create User</h3>
				</div>


			

				<!-- /.card-header -->
				<!-- form start -->
				<form id="create-form">
					@csrf

					<!--we need to make it appear when their is an error  , $errors = we make validation auto request validator return array (errors)
					result of failer >> errors of validation rules  the next step we need to show the errors (li) >>loop >>
					value old >> return old data 
					-->
				      
				  <div class="card-body">
					<div class="form-group">
					  <label for="name">Name</label>
					  <input type="text" class="form-control" name="name" id="name" placeholder="Enter name">
					</div>
					<div class="form-group">
					  <label for="email">Email</label>
					  <input type="email" class="form-control"   name="email" id="email" placeholder="Enter Email">
					</div>
				
				  </div>
				  <!-- /.card-body -->
  
				  <div class="card-footer">
					<button type="button" onclick="performStore()" class="btn btn-primary">Submit</button>
				  </div>
				</form>
			  </div>
			  <!-- /.card -->
  
		
  
			</div>
			<!--/.col (left) -->
		
		  </div>
		  <!-- /.row -->
		</div><!-- /.container-fluid -->
	  </section>
	  <!-- /.content -->
@endsection
 

@section('scripts')
<!-- Select2 -->
<script src="{{asset('cms/plugins/select2/js/select2.full.min.js')}}"></script>

<script>
	$('.roles').select2({
	theme: 'bootstrap4' //Bootstrap
	});
	function performStore(){
		
		let data ={
           name :document.getElementById('name').value,
		   email:document.getElementById('email').value,
		}
		store('/cms/admin/users',data);
	}
</script>

@endsection

resources/views/cms/users/edit.blade.php
@extends('cms.parent')

@section('title','DEMO')
@section('page-large-name','Library System')
@section('page-small-name','Admin')

@section('styles')
<!-- Select2 -->
<link rel="stylesheet" href="{{asset('cms/plugins/select2/css/select2.min.css')}}">
<link rel="stylesheet" href="{{asset('cms/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css')}}">
@endsection

@section('content')
    <!-- Main content -->
    <section class="content">
		<div class="container-fluid">
		  <div class="row">
			<!-- left column -->
			<div class="col-md-12">
			  <!-- general form elements -->
			  <div class="card card-primary">
				<div class="card-header">
				  <h3 class="card-title">Edit  User</h3>
				</div>


			

				<!-- /.card-header -->
				<!-- form start -->
				<form id="create-form">
					@csrf

					<!--we need to make it appear when their is an error  , $errors = we make validation auto request validator return array (errors)
					result of failer >> errors of validation rules  the next step we need to show the errors (li) >>loop >>
					value old >> return old data 
					-->
				      
				  <div class="card-body">
					<div class="form-group">
					  <label for="name">Name</label>
					  <input type="text" class="form-control" name="name" value="{{$user->name}}"
					   id="name" placeholder="Enter name">
					</div>
					<div class="form-group">
					  <label for="email">Email</label>
					  <input type="email" class="form-control"   name="email" value="{{$user->email}}
					  "id="email" placeholder="Enter Email">
					</div>
				
				  </div>
				  <!-- /.card-body -->
  
				  <div class="card-footer">
					<button type="button" onclick="performUpdate()" class="btn btn-primary">Submit</button>
				  </div>
				</form>
			  </div>
			  <!-- /.card -->
  
		
  
			</div>
			<!--/.col (left) -->
		
		  </div>
		  <!-- /.row -->
		</div><!-- /.container-fluid -->
	  </section>
	  <!-- /.content -->
@endsection
 

@section('scripts')
<!-- Select2 -->
<script src="{{asset('cms/plugins/select2/js/select2.full.min.js')}}"></script>

<script>
	$('.roles').select2({
	theme: 'bootstrap4' //Bootstrap
	});
	function performUpdate(){
		
		let data ={
           name :document.getElementById('name').value,
		   email:document.getElementById('email').value,
		}
		update('/cms/admin/users/{{$user->id}}' ,data, '/cms/admin/users'); //ref
	}
</script>

@endsection

resources/views/cms/users/index.blade.php
@extends('cms.parent')

@section('title','Users')
@section('page-large-name','Users')
@section('page-small-name','Show')

@section('styles')

@endsection

@section('content')
<!-- Main content -->
<section class="content">
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-12">
				<div class="card">
					<div class="card-header">
						<h3 class="card-title">Bordered Table</h3>
					</div>
					<!-- /.card-header -->
					<div class="card-body">
						<table class="table table-bordered table-striped table-hover">
							<thead>
								<tr>
									<th style="width: 10px">#</th>
									<th>Name</th>
									<th>Email</th>
									<th>Permissions</th>
									<th>Created At</th>
									<th>Updated At</th>
									<th>Settings</th>
								</tr>
							</thead>
							<tbody>
								@foreach ($users as $user)
								<tr>
									<td>{{$user->id}}</td>
									<td>{{$user->name}}</td>
									<td>
										<span class="badge bg-info">{{$user->email}}</span>
									</td>
									<td>
										<a href="{{route('user-permissions.show' , $user->id)}}" class="btn btn-block btn-warning btn-sm">
											({{$user->permissions_count}}) Permission/s
										</a>
									</td>
									<td>{{$user->created_at->format('y-m-d H:ma')}}</td>
									<td>{{$user->updated_at->format('y-m-d H:ma')}}</td>
									<td>
										<div class="btn-group">
											<!--Edit  Button-->
											<a href="{{route('users.edit',$user->id)}}" class="btn btn-info">
												<i class="fas fa-edit"></i>
											</a>
											<!--Java Script way-->
											<a onclick="performdelete({{$user->id}}, this )" class="btn btn-danger">
												<i class="fas fa-trash"></i>
											</a>
											<!--WE Can't sent a check request  without using Form , if we sent the method as get then will be cause a conflict 
									because their is the same route as the delete (show)   so we put the type post to avoid conflict and gose direct to delete 
								-->


											<!--Delete Button traditional way-->

											{{-- <form method="POST" action="{{route('categories.destroy',$user->id)}}">
											@csrf
											@method('DELETE')
											<button type="submit" class="btn btn-danger">
												<i class="fas fa-trash"></i>
											</button>
											</form> --}}


										</div>
									</td>

								</tr>
								@endforeach
								<!--For Knowledge-->
								{{--@if ($user->visible)
						<td>True</td>
					     @else
					     <td>False</td>
					     @endif--}}

							</tbody>
						</table>
					</div>
					<!-- /.card-body -->

				</div>
				<!-- /.card -->


			</div>
			<!-- /.col -->
		</div>
		<!-- /.row -->
	</div><!-- /.container-fluid -->
</section>
<!-- /.content -->
@endsection


@section('scripts')
<script>
	function performdelete(id ,ref){
		confirmDestroy('/cms/admin/users',id ,ref)
	 }
</script>


@endsection

{{-- Swal.fire(
	'Deleted!',
	'Your file has been deleted.',
	'success'
  ) --}}

resources/views/cms/users/user-permission.blade.php
@extends('cms.parent')

@section('title','User-Permissions')
@section('page-large-name','User-Permission')
@section('page-small-name','Index')

@section('styles')
<link rel="stylesheet" href="{{asset('cms/plugins/icheck-bootstrap/icheck-bootstrap.min.css')}}">
@endsection

@section('content')
    <!-- Main content -->
    <section class="content">
		<div class="container-fluid">
		  <div class="row">
			<div class="col-md-12">
			  <div class="card">
				<div class="card-header">
				  <h3 class="card-title">{{$user->name}} Permission </h3>
				</div>
				<!-- /.card-header -->
				<div class="card-body">
				  <table class="table table-bordered table-striped table-hover">
					<thead>
					  <tr>
						<th style="width: 10px">#</th>
						<th>Permission Name</th>
						<th>Permission Guard</th>
						<th>Assigned</th>
					  </tr>
					</thead>
					<tbody>
						@foreach ($permissions as $permission)
						<tr>
							<td>{{$permission->id}}</td>
							<td>{{$permission->name}}</td>
						
							<td>
								<!--We need to send number of permissions-->
								<span class="badge bg-info">{{$permission->guard_name}}</span>
							</td>	
							<td>
								
							<div class="icheck-success d-inline">
								<input type="checkbox" 
								 onclick="assinedPermission('{{$user->id}}','{{$permission->id}}')"
								@if($permission->assigned)
								checked 
								@endif
								id="permission_{{$permission->id}}">
								<label for="permission_{{$permission->id}}">
								</label>
							</div>
							</td>
							
						  </tr>
						@endforeach
						<!--For Knowledge-->
						{{--@if ($data->visible)
						<td>True</td>
					     @else
					     <td>False</td>
					     @endif--}}
					
					</tbody>
				  </table>
				</div>
				<!-- /.card-body -->
		
			  </div>
			  <!-- /.card -->
  
			
			</div>
			<!-- /.col -->
		  </div> 
		  <!-- /.row -->
		</div><!-- /.container-fluid -->
	  </section>
	  <!-- /.content -->
@endsection


@section('scripts')
 <script>
	 
	//we need to add permissions for role 
	//every check on permission will be add 
	function assinedPermission(userId , permissionId){
	axios.post('/cms/admin/permissions/user-permissions' , {
		user_id :userId,
		permission_id :permissionId
	})
	.then(function (response) {
	// handle success code 2xx
	console.log(response);
	toastr.success(response.data.message)
	})
	.catch(function (error) {
	// handle error 4xx 5xx
	console.log(error);
	toastr.error(error.response.data.message)
	});
	
	}
	 </script>

@endsection

{{-- Swal.fire(
	'Deleted!',
	'Your file has been deleted.',
	'success'
  ) --}}