routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\Authcontroller;
use App\Http\Controllers\BookController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CountryController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\RolePermissionController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\UserPermissionController;
use App\Http\Middleware\checkAge;
use App\Mail\WelComeEmail;
use App\Models\Category;
use GuzzleHttp\Middleware;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/* Route::get('/', function () {
    return view('welcome');
}); */
//admin + user (web) both > login + logout 
//admin >> categories + countries 
//user > books 
//we need to add guard as parameter , dynamic attribute 

Route::prefix('cms/')->middleware('guest:admin,user')->group(function(){
  //  Route::view('login','cms.auth.login')->name('cms.login');
  Route::get('{guard}/login',[Authcontroller::class,'showlogin'])->name('cms.login');
  Route::post('login',[Authcontroller::class,'login']);
});

Route::prefix('cms/admin')->middleware('auth:admin')->group(function (){
  /*Note: route resbonsible to show >> index */
  Route::resource('admins', AdminController::class);
  Route::resource('roles', RoleController::class);
  Route::resource('permissions', PermissionController::class);
  
  Route::resource('permissions/role', RolePermissionController::class);
  Route::resource('permissions/user-permissions', UserPermissionController::class);
  Route::resource('users', UserController::class);
  

});

Route::prefix('cms/admin')->middleware('auth:admin,user')->group(function () {
  Route::view('/', 'cms.empty');
  Route::resource('books', BookController::class);
  Route::resource('categories', CategoryController::class);
  Route::resource('countries', CountryController::class);
  Route::get('change-password', [Authcontroller::class, 'showChangePassword'])->name('cms.changePassword');
  Route::post('change-password', [Authcontroller::class, 'changePassword']);
  Route::get('logout', [Authcontroller::class, 'logout'])->name('cms.logout');
});


Route::prefix('mail')->group(function(){
      Route::get('welcome',function(){
        return new WelComeEmail(); //markdown blade 
      });
});




//First way >> installation method of middleware 
// Route::get('news',function(){
//    return 'welcome to news page ';
// })->middleware('age:22',);


//second way 
// Route::get('news',function(){
  
//   /// return 'welcome to news page ';
//    return response()->json(['status'=>'success','active'=>true]);
//  })->middleware(checkAge::class);

 //third way 
//  Route::middleware('age:22',)->get('news',function(){
//     return 'welcome to news page ';
//  });

//forth way 
// Route::middleware('age:22',)->group(function(){
//   Route::get('news',function(){
//    return 'welcome to news page';
//      })->withoutMiddleware('age');
// });

app/Models/Book.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Book extends Model
{
    use HasFactory , SoftDeletes;  //first add trate , then we add a new col in creatte table migration >>Deleted At 
    //we have five process > Trashed , withtrash , onlytrash , forcedelete , restore
    //السوفت ديليت تحويل النل الى قيمة
    public function getVisibilityStatusAttribute()
    {
        return $this->is_visible ? 'visible' : 'Hidden';
    }

    
    public function getlanguageNameAttribute(){
        return $this->language == 'en' ? 'English' : 'Arabic';
    }

    public function category(){

        return $this->belongsTo(Category::class,'category_id','id');

    }
}

app/Http/Controllers/API/BookController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use App\Models\Book;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class BookController extends Controller
{
    /**
     * Display a listing of the resource. api 5 function 
     * //create and edit are deleted 
     * //the user can't reach books if he is not register >> should be authenticated user >>middleware on guard api 
     * //should token sent 
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        // $books =Book::all();
        //IF we have a huge number of books and we need just 10 books in the page 
        //we use pagenation (10)
        // $books = Book::paginate(1); //for web more details 
        $books = Book::simplePaginate(10); //for mobile  more useable 
        //create object and set inside it listed data 
        return response()->json(['status'=>true , 'message'=>'sucess' , 'data'=>$books]);
    }
 
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $validator = Validator($request->all(), [

            'name' => 'required|string|min:3|max:100',
            'year' => 'required|numeric|digits:4',
            'language' => 'required|string|in:en,ar',
            'quantity' => 'required|integer|min:1',
            'visible' => 'required|boolean',
            'image' => 'nullabel|image|mimes:jpg,png|size:2048',
            'category_id' => 'required|integer|exists:categories,id' //

        ]);
        if (!$validator->fails()) {
            $book = new Book();
            $book->name = $request->get('name');
            $book->year = $request->get('year');
            $book->language = $request->get('language');
            $book->quantity = $request->get('quantity');
            $book->is_visible = $request->get('visible');
            $book->category_id = $request->get('category_id');


            $isSaved = $book->save();
            //  Category::findOrFail($request->get('category_id'))->books->save($book);

            return response()->json(
                ['message' => $isSaved ? 'Saved successfully' : ' Failed to save'],
                $isSaved ? Response::HTTP_CREATED : Response::HTTP_BAD_REQUEST
            );
        } else {
            return response()->json(
                ['message' => $validator->getMessageBag()->first()],
                Response::HTTP_BAD_REQUEST
            );
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Book $book)
    {
        //
        $validator = Validator($request->all(), [

            'name' => 'required|string|min:3|max:100',
            'year' => 'required|numeric|digits:4',
            'language' => 'required|string|in:en,ar',
            'quantity' => 'required|integer|min:1',
            'visible' => 'required|boolean',
            'image' => 'nullabel|image|mimes:jpg,png|size:2048',
            'category_id' => 'required|integer|exists:categories,id' //

        ]);
        if (!$validator->fails()) {
            $book->name = $request->get('name');
            $book->year = $request->get('year');
            $book->language = $request->get('language');
            $book->quantity = $request->get('quantity');
            $book->is_visible = $request->get('visible');
            $book->category_id = $request->get('category_id');


            $isSaved = $book->save();
            //  Category::findOrFail($request->get('category_id'))->books->save($book);

            return response()->json(
                ['message' => $isSaved ? 'Saved successfully' : ' Failed to save'],
                $isSaved ? Response::HTTP_CREATED : Response::HTTP_BAD_REQUEST
            );
        } else {
            return response()->json(
                ['message' => $validator->getMessageBag()->first()],
                Response::HTTP_BAD_REQUEST
            );
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        // $deleted = Book::destroy($id);
        $deleted = Book::findOrFail($id)->delete();
        return response()->json(['status'=>$deleted , 'message'=> $deleted ? 'Deleted successfully' : 'Deleted faild'],
    $deleted ? Response::HTTP_OK : Response::HTTP_BAD_REQUEST
    
    );
    }
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use App\Models\Book;
use App\Models\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Symfony\Component\HttpFoundation\Response;

class BookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        //by defualt withoutTrashed 
        //  $books = Book::with('category')->get(); // this will retrun all  books that the deleted at value is NUll
        //  $books = Book::with('category')->onlyTrashed()->get(); //just deleted books
        // $books = Book::with('category')->withoutTrashed()->get();
        $books = Book::with('category')->withTrashed()->get(); //return also deleted books with non deleted
        // بدنا نرجع الداتا 
        //if web > view   mobile api > json 
        //بدنا نفحص ال expect json or work on guard and this is the best way 
        //type of guard > api json  , web view 
        if (auth('api')->check()) {
            return response()->json(['data' => $books]);
        } else {
            //view 
            return response()->view('cms.Books.index', ['books' => $books]);
        }
        //we have anthor method to check the api 
        //    if(request()->expectsjson()){
        //   js , node js , vue js , api 
        // In header we add Key Accept  - value appliaction/json 
        //    }


    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $categories = Category::where('is_visible', true)->get();
        return  response()->view('cms.Books.create', ['categories' => $categories]);

        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $validator = Validator($request->all(), [
            'name' => 'required|string|min:3|max:100',
            'year' => 'required|numeric|digits:4',
            'language' => 'required|string|in:en,ar',
            'quantity' => 'required|integer|min:1',
            // 'visible' => 'required|boolean',
            'visible' => 'required|in:true,false',
            'image' => 'required|image|mimes:jpg,png|max:2048',
            'category_id' => 'required|integer|exists:categories,id'
        ]);

        if (!$validator->fails()) {
            $book = new Book();
            $book->name = $request->get('name');
            $book->year = $request->get('year');
            $book->language = $request->get('language');
            $book->quantity = $request->get('quantity');
            $book->category_id = $request->get('category_id');
            // Category::findOrFail($request->get('category_id'))->books()->save($book);

            if ($request->hasFile('image')) {
                $image = $request->file('image');
                $imageName = time() . '_' . $book->name . '.' . $image->getClientOriginalExtension();
                $request->file('image')->storePubliclyAs('books', $imageName, ['disk' => 'public']);
                $book->image = $imageName;
            }
            $isSaved = $book->save();

            return response()->json([
                'message' => $isSaved ? 'Saved successfully' : 'Failed to create new book!'
            ], $isSaved ? Response::HTTP_CREATED : Response::HTTP_BAD_REQUEST);
        } else {
            return response()->json([
                'message' => $validator->getMessageBag()->first()
            ], Response::HTTP_BAD_REQUEST);
        }
    }



    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function show(Book $book)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function edit(Book $book)
    {
        //
        $categories = Category::where('is_visible', true)->get();
        return response()->view('cms.Books.edit', ['book' => $book, 'categories' => $categories]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Book $book)
    {
        //
        $validator = Validator($request->all(), [
            'name' => 'required|string|min:3|max:100',
            'year' => 'required|numeric|digits:4',
            'language' => 'required|string|in:en,ar',
            'quantity' => 'required|integer|min:1',
            // 'visible' => 'required|boolean',
            'visible' => 'required|in:true,false',
            'image' => 'nullable|image|mimes:jpg,png|max:2048',
            'category_id' => 'required|integer|exists:categories,id'
        ]);

        if (!$validator->fails()) {
            $book->name = $request->get('name');
            $book->year = $request->get('year');
            $book->language = $request->get('language');
            $book->quantity = $request->get('quantity');
            $book->category_id = $request->get('category_id');
            // Category::findOrFail($request->get('category_id'))->books()->save($book);

            if ($request->hasFile('image')) {
                // Storage::delete("/books/$book->image");
                Storage::disk('public')->delete("books/$book->image"); //عشان يحذف الصور القديمة
                //delete path
                $image = $request->file('image');
                $imageName = time() . '_' . $book->name . '.' . $image->getClientOriginalExtension();
                $request->file('image')->storePubliclyAs('books', $imageName, ['disk' => 'public']);
                $book->image = $imageName;
            }
            $isSaved = $book->save();

            return response()->json([
                'message' => $isSaved ? 'Saved successfully' : 'Failed to create new book!'
            ], $isSaved ? Response::HTTP_CREATED : Response::HTTP_BAD_REQUEST);
        } else {
            return response()->json([
                'message' => $validator->getMessageBag()->first()
            ], Response::HTTP_BAD_REQUEST);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        //اذا بدي احذف حذف تام = forcdelete
        //softdelete is event gose on database to convert softdelete to deleted At col

        //$isDeleted = $book->delete();
        // return response()->json(
        //     [
        //         'icon' => $isDeleted ? 'success' : ' danger',
        //         'title' => $isDeleted ? 'Deleded successfully' : 'Failed to delete'
        //     ],
        //     $isDeleted ? Response::HTTP_OK : Response::HTTP_BAD_REQUEST
        // );
        $book = Book::withTrashed()->findOrFail($id);
        $message = '';
        if ($book->trashed()) {
            $status = $book->restore();
            $message = 'Book restored successfuly';
        } else {
            //    $book = $book->delete();
            //         $message = 'Book Deleted successfuly';
            $isDeleted = $book->delete();
            return response()->json(
                [
                    'icon' => $isDeleted ? 'success' : ' danger',
                    'title' => $isDeleted ? 'Deleded successfully' : 'Failed to delete'
                ],
                $isDeleted ? Response::HTTP_OK : Response::HTTP_BAD_REQUEST
            );
        }
        if ($status) {
            return response()->json(['title' =>  $message, 'icon' => 'success']); //key>>string""  value>>int object double boolean array of any type or array of json  //begin with objects or array
        } else {
            return response()->json(['title' => 'Process failed', 'icon' => 'danger']);
        }
    }
}

resources/views/cms/Books/create.blade.php
@extends('cms.parent')

@section('title','DEMO')
@section('page-large-name','Library System')
@section('page-small-name','Books')

@section('styles')
<!-- Select2 -->
<link rel="stylesheet" href="{{asset('cms/plugins/select2/css/select2.min.css')}}">
<link rel="stylesheet" href="{{asset('cms/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css')}}">
@endsection

@section('content')
<!-- Main content -->
<section class="content">
	<div class="container-fluid">
		<div class="row">
			<!-- left column -->
			<div class="col-md-12">
				<!-- general form elements -->
				<div class="card card-primary">
					<div class="card-header">
						<h3 class="card-title">Create Book</h3>
					</div>




					<!-- /.card-header -->
					<!-- form start -->
					<form>
						@csrf

						<!--we need to make it appear when their is an error  , $errors = we make validation auto request validator return array (errors)
					result of failer >> errors of validation rules  the next step we need to show the errors (li) >>loop >>
					value old >> return old data 
					-->

						<div class="card-body">
							<div class="form-group">
								<label>Category</label>
								<select class="form-control categories" id="category_id" style="width: 100%;">
									{{-- <option selected="selected">Alabama</option> --}}
									@foreach ($categories as $category )
									<option value="{{$category->id}}">{{$category->name}}</option>
									@endforeach


								</select>
							</div>
							<div class="form-group">
								<label for="name">Name</label>
								<input type="text" class="form-control" name="name" id="name" placeholder="Enter name">
							</div>

							<div class="form-group">
								<label for="year">Year</label>
								<input type="number" class="form-control" id="year" placeholder="year">
							</div>

							<div class="form-group">
								<label>Language</label>
								<select class="form-control languages" id="language" style="width: 100%;">
									<option value="en">English</option>
									<option value="ar">Arabic</option>


								</select>
							</div>


							<div class="form-group">
								<label for="quantity">Quantity</label>
								<input type="number" class="form-control" id="quantity" placeholder="quantity">
							</div>


							<div class="form-group">
								<!-- <label for="customFile">Custom File</label> -->
								<label for="book_image">Image</label>
								<div class="custom-file">
									<input type="file" class="custom-file-input" id="book_image">
									<label class="custom-file-label" for="book_image">Choose file</label>
								</div>
							</div>

							<div class="form-group">
								<div class="custom-control custom-switch">
									<input type="checkbox" class="custom-control-input" name="visible" id="visible"
										checked>
									<label class="custom-control-label" for="visible">visible</label>
								</div>
							</div>

						</div>
						<!-- /.card-body -->

						<div class="card-footer">
							<button type="button" onclick="performStore()" class="btn btn-primary">Submit</button>
						</div>
					</form>
				</div>
				<!-- /.card -->



			</div>
			<!--/.col (left) -->

		</div>
		<!-- /.row -->
	</div><!-- /.container-fluid -->
</section>
<!-- /.content -->
@endsection


@section('scripts')
<!-- Select2 -->
<script src="{{asset('cms/plugins/select2/js/select2.full.min.js')}}"></script>

<script>
	$('.categories').select2({
      theme: 'bootstrap4' //Bootstrap 
    });

	$('.languages').select2({
      theme: 'bootstrap4' //Bootstrap 
    });



	//Book store 
	function performStore(){
		// let data = {
		// name: document.getElementById('name').value,
		// year:document.getElementById('year').value,
		// quantity:document.getElementById('quantity').value,
		// category_id: document.getElementById('category_id').value,
		// language: document.getElementById('language').value,
		// visible: document.getElementById('visible').checked,
		// }
		
		let formData = new FormData();
		formData.append('name',document.getElementById('name').value);
		formData.append('year',document.getElementById('year').value);
		formData.append('quantity',document.getElementById('quantity').value);
		formData.append('category_id',document.getElementById('category_id').value);
		formData.append('language',document.getElementById('language').value);
		formData.append('visible',document.getElementById('visible').checked);
		formData.append('image',document.getElementById('book_image').files[0]);
		store('/cms/admin/books',formData);
		}
</script>

@endsection

resources/views/cms/Books/edit.blade.php
@extends('cms.parent')

@section('title','DEMO')
@section('page-large-name','DEMO')
@section('page-small-name','Demo')

@section('styles')
<!-- Select2 -->
<link rel="stylesheet" href="{{asset('cms/plugins/select2/css/select2.min.css')}}">
<link rel="stylesheet" href="{{asset('cms/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css')}}">
@endsection

@section('content')
<!-- Main content -->
<section class="content">
	<div class="container-fluid">
		<div class="row">
			<!-- left column -->
			<div class="col-md-12">
				<!-- general form elements -->
				<div class="card card-primary">
					<div class="card-header">
						<h3 class="card-title">Edit Book</h3>
					</div>

					<!-- /.card-header -->
					<!-- form start -->
					<form>
						@csrf
						<div class="card-body">
							<div class="form-group">
								<label>Category</label>
								<select class="form-control categories" id="category_id" style="width: 100%;">
									{{-- <option selected="selected">Alabama</option> --}}
									@foreach ($categories as $category)
									<option value="{{$category->id}}" @if($category->id == $book->category_id) selected
										@endif>{{$category->name}}</option>
									@endforeach
								</select>
							</div>
							<div class="form-group">
								<label for="name">Name</label>
								<input type="text" class="form-control" value={{$book->name}} id="name"
									placeholder="Enter name">
							</div>
							<div class="form-group">
								<label for="description">Year</label>
								<input type="number" class="form-control" value={{$book->year}} id="year"
									placeholder="Year">
							</div>
							<div class="form-group">
								<label>Language</label>
								<select class="form-control languages" id="language" style="width: 100%;">
									<option value="en" @if($book->language == 'en') selected @endif>English</option>
									<option value="ar" @if($book->language == 'ar') selected @endif>Arabic</option>
								</select>
							</div>
							<div class="form-group">
								<label for="description">Quantity</label>
								<input type="number" class="form-control" value='{{$book->quantity}}' id="quantity"
									placeholder="Quantity">
							</div>
							<div class="form-group">
								<!-- <label for="customFile">Custom File</label> -->
								<label for="description">Image</label>
								<div class="custom-file">
									<input type="file" class="custom-file-input" id="book_image">
									<label class="custom-file-label" for="customFile">Choose file</label>
								</div>
							</div>

							<div class="form-group">
								<div class="custom-control custom-switch">
									<input type="checkbox" class="custom-control-input" name="visible" id="visible"
										@if($book->is_visible) checked @endif>
									<label class="custom-control-label" for="visible">Visible</label>
								</div>
							</div>
						</div>
						<!-- /.card-body -->

						<div class="card-footer">
							<button type="button" onclick="performUpdate()" class="btn btn-primary">Submit</button>
						</div>
					</form>
				</div>
				<!-- /.card -->
			</div>
			<!--/.col (left) -->
		</div>
		<!-- /.row -->
	</div><!-- /.container-fluid -->
</section>
<!-- /.content -->
@endsection

@section('scripts')
<!-- Select2 -->
<script src="{{asset('cms/plugins/select2/js/select2.full.min.js')}}"></script>
<script>
	//Initialize Select2 Elements
    $('.categories').select2({
        theme: 'bootstrap4'
    });
    $('.languages').select2({
        theme: 'bootstrap4'
    });

    function performUpdate(){
        // let data = {
        //     name: document.getElementById('name').value,
        //     year:document.getElementById('year').value,
        //     quantity:document.getElementById('quantity').value,
        //     category_id: document.getElementById('category_id').value,
        //     language: document.getElementById('language').value,
        //     visible: document.getElementById('visible').checked,
        // }

        let formData = new FormData();
        formData.append('_method','PUT');//post
        formData.append('name',document.getElementById('name').value);
        formData.append('year',document.getElementById('year').value);
        formData.append('quantity',document.getElementById('quantity').value);
        formData.append('category_id',document.getElementById('category_id').value);
        formData.append('language',document.getElementById('language').value);
        formData.append('visible',document.getElementById('visible').checked);
        if(document.getElementById('book_image').files[0] != undefined){
            formData.append('image',document.getElementById('book_image').files[0]);
        }
        store('/cms/admin/books/{{$book->id}}',formData);
    }
</script>
@endsection

resources/views/cms/Books/index.blade.php
@extends('cms.parent')

@section('title','Books')
@section('page-large-name','Books')
@section('page-small-name','Index-show')

@section('styles')

@endsection

@section('content')
    <!-- Main content -->
    <section class="content">
		<div class="container-fluid">
		  <div class="row">
			<div class="col-md-12">
			  <div class="card">
				<div class="card-header">
				  <h3 class="card-title">Bordered Table</h3>
				</div>
				<!-- /.card-header -->
				<div class="card-body">
				  <table class="table table-bordered table-striped table-hover">
					<thead>
					  <tr>
						<th style="width: 10px">#</th>
						<th>Image</th>
						<th>Name</th>
						<th>Category</th>
						<th>Year</th>
						<th>language</th>
						<th>Quantity</th>
						<th>Visible</th>
						<th>Created At</th>
						<th>Updated At</th>
						<th>Settings</th>
					  </tr>
					</thead>
					<tbody>
						@foreach ($books as $book)
						<tr>
							<td>{{$book->id}}</td>
							<td>
								<img class="img-circle img-bordered-sm"  height="60" width="60"
								src="{{Storage::url('books/'.$book->image)}}" alt="user image">
							</td>
							<td>{{$book->name}}</td>
							<td>{{$book->category->name}}</td>
							<td>
								<span class="badge bg-info">({{$book->year}})</span>
							</td>
							<td>
								<span class="badge bg-success">	{{$book->language_name}}</span>
							</td>
							<td>
								<span class="badge bg-primary">({{$book->quantity}}) book/s</span>
							</td>
							<td>
								<span class="badge bg-info">({{$book->visibility_status}})</span>
							</td>
							
							<td>{{$book->created_at->format('y-m-d H:ma')}}</td>
							<td>{{$book->updated_at->format('y-m-d H:ma')}}</td>
							<td>
								<div class="btn-group">
										<!--Edit  Button-->
									<a href="{{route('books.edit',$book->id)}}" class="btn btn-info">
									  <i class="fas fa-edit"></i>  
									</a>
	<!--Java Script way-->             
	                                @if($book->trashed())
									<a onclick="deleteBook({{$book->id}}, this )" class="btn btn-warning">
										<i class="fas fa-trash-restore"></i>
										{{-- <i class="fas fa-trash-restore"></i> --}}
									</a>
									@else
                                         <a onclick="deleteBook({{$book->id}}, this )" class="btn btn-danger">
												<i class="fas fa-trash"></i>
											</a>
									@endif
								
									<!--WE Can't sent a check request  without using Form , if we sent the method as get then will be cause a conflict 
									because their is the same route as the delete (show)   so we put the type post to avoid conflict and gose direct to delete 
								-->
								<!--Delete Button traditional way-->

									{{-- <form method="POST" action="{{route('categories.destroy',$data->id)}}"> 
										@csrf 
										@method('DELETE')
									<button type="submit" class="btn btn-danger">
									  <i class="fas fa-trash"></i>
									</button>
								</form> --}}
							
							
								  </div>
							</td>
							
						  </tr>
						@endforeach
						<!--For Knowledge-->
						{{--@if ($data->visible)
						<td>True</td>
					     @else
					     <td>False</td>
					     @endif--}}
					
					</tbody>
				  </table>
				</div>
				<!-- /.card-body -->
		
			  </div>
			  <!-- /.card -->
  
			
			</div>
			<!-- /.col -->
		  </div> 
		  <!-- /.row -->
		</div><!-- /.container-fluid -->
	  </section>
	  <!-- /.content -->
@endsection


@section('scripts')
 <script>
	 
	 function deleteBook(id ,ref){
		confirmDestroy('/cms/admin/books',id ,ref)
	 }
	 </script>

@endsection

{{-- Swal.fire(
	'Deleted!',
	'Your file has been deleted.',
	'success'
  ) --}}