routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\Authcontroller;
use App\Http\Controllers\BookController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CountryController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\RolePermissionController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\UserPermissionController;
use App\Http\Middleware\checkAge;
use App\Mail\WelComeEmail;
use App\Models\Category;
use GuzzleHttp\Middleware;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/* Route::get('/', function () {
    return view('welcome');
}); */
//admin + user (web) both > login + logout 
//admin >> categories + countries 
//user > books 
//we need to add guard as parameter , dynamic attribute 

Route::prefix('cms/')->middleware('guest:admin,user')->group(function(){
  //  Route::view('login','cms.auth.login')->name('cms.login');
  Route::get('{guard}/login',[Authcontroller::class,'showlogin'])->name('cms.login');
  Route::post('login',[Authcontroller::class,'login']);
});

Route::prefix('cms/admin')->middleware('auth:admin')->group(function (){
  /*Note: route resbonsible to show >> index */
  Route::resource('admins', AdminController::class);
  Route::resource('roles', RoleController::class);
  Route::resource('permissions', PermissionController::class);
  
  Route::resource('permissions/role', RolePermissionController::class);
  Route::resource('permissions/user-permissions', UserPermissionController::class);
  Route::resource('users', UserController::class);
  

});

Route::prefix('cms/admin')->middleware('auth:admin,user')->group(function () {
  Route::view('/', 'cms.empty');
  Route::resource('books', BookController::class);
  Route::resource('categories', CategoryController::class);
  Route::resource('countries', CountryController::class);
  Route::get('change-password', [Authcontroller::class, 'showChangePassword'])->name('cms.changePassword');
  Route::post('change-password', [Authcontroller::class, 'changePassword']);
  Route::get('logout', [Authcontroller::class, 'logout'])->name('cms.logout');
});


Route::prefix('mail')->group(function(){
      Route::get('welcome',function(){
        return new WelComeEmail(); //markdown blade 
      });
});




//First way >> installation method of middleware 
// Route::get('news',function(){
//    return 'welcome to news page ';
// })->middleware('age:22',);


//second way 
// Route::get('news',function(){
  
//   /// return 'welcome to news page ';
//    return response()->json(['status'=>'success','active'=>true]);
//  })->middleware(checkAge::class);

 //third way 
//  Route::middleware('age:22',)->get('news',function(){
//     return 'welcome to news page ';
//  });

//forth way 
// Route::middleware('age:22',)->group(function(){
//   Route::get('news',function(){
//    return 'welcome to news page';
//      })->withoutMiddleware('age');
// });

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Spatie\Permission\Models\Role;
use Symfony\Component\HttpFoundation\Request as HttpFoundationRequest;
use Symfony\Component\HttpFoundation\Response;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

     //Role created based on spesifc guard and the user take role that have permission from the same guard
     //
    public function index()
    {
        //
        // $roles = Role::all();      
        //to get number of permissions for the role 
        $roles = Role::withCount('permissions')->get();
        return response()->view('cms.roles.index',['roles'=>$roles]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return response()->view('cms.roles.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $validator = Validator($request->all(),[
              'name'=>'required|string|min:3|max:40',
              'guard'=> 'required|string|in:user,admin',
        ]);
        if(!$validator->fails()){
                $role = new Role();
                $role->name =$request->get('name');
                $role->guard_name =$request->get('name');
                $isSaved =$role->save();
                 return response()->json(['message'=> $isSaved ? 'Saved successfully': 'Failed to save'],$isSaved ? Response::HTTP_CREATED : Response::HTTP_BAD_REQUEST);
        }else{
                return response()->json(['message'=> $validator->getMessageBag()->first(),Response::HTTP_BAD_REQUEST]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Role $role)
    {
        //
        // $isDeleted = $role->delete();
        //  return response()->json(['message'=>$isDeleted ? 'Deleted successfully' : 'Failed to delete role'], 
        //  $isDeleted ? Response::HTTP_OK : Response::HTTP_BAD_REQUEST);

        $deleted = $role->delete();
        if ($deleted) {
            return response()->json(['title' => 'Deleted successfully', 'icon' => 'success']); //key>>string""  value>>int object double boolean array of any type or array of json  //begin with objects or array
        } else {
            return response()->json(['title' => 'Deleted failed', 'icon' => 'warining']);
        }
    }
}

resources/views/cms/roles/create.blade.php
@extends('cms.parent')

@section('title','DEMO')
@section('page-large-name','Library System')
@section('page-small-name','Roles')

@section('styles')
 <!-- Select2 -->
 <link rel="stylesheet" href="{{asset('cms/plugins/select2/css/select2.min.css')}}">
 <link rel="stylesheet" href="{{asset('cms/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css')}}">
@endsection

@section('content')
    <!-- Main content -->
    <section class="content">
		<div class="container-fluid">
		  <div class="row">
			<!-- left column -->
			<div class="col-md-12">
			  <!-- general form elements -->
			  <div class="card card-primary">
				<div class="card-header">
				  <h3 class="card-title">Create Role</h3>
				</div>


			

				<!-- /.card-header -->
				<!-- form start -->
				<form method="POST" action="{{route('roles.store')}}" >
					@csrf

					<!--we need to make it appear when their is an error  , $errors = we make validation auto request validator return array (errors)
					result of failer >> errors of validation rules  the next step we need to show the errors (li) >>loop >>
					value old >> return old data 
					-->
				      
				  <div class="card-body">
					<div class="form-group">
						<label>Guard</label>
						<select class="form-control guard" id ="guard" style="width: 100%;">
						  {{-- <option selected="selected">Alabama</option> --}}
						  
						  <option  value="admin">Admin</option>
						  <option value="user">User</option>

						  
						
						</select>
					  </div>
					<div class="form-group">
					  <label for="name">Name</label>
					  <input type="text" class="form-control"  name="name" id="name" placeholder="Enter name">
					</div>

				  </div>
				  <!-- /.card-body -->
  
				  <div class="card-footer">
					<button type="button" onclick="performStore()" class="btn btn-primary">Submit</button>
				  </div>
				</form>
			  </div>
			  <!-- /.card -->
  
		
  
			</div>
			<!--/.col (left) -->
		
		  </div>
		  <!-- /.row -->
		</div><!-- /.container-fluid -->
	  </section>
	  <!-- /.content -->
@endsection
 

@section('scripts')
<!-- Select2 -->
<script src="{{asset('cms/plugins/select2/js/select2.full.min.js')}}"></script>

<script>
 $('.guard').select2({
      theme: 'bootstrap4' //Bootstrap 
    });


	//Book store 
	function performStore(){
     let data ={
		 name :document.getElementById('name').value,
		  guard :document.getElementById('guard').value,
		 
	 }

	 store('/cms/admin/roles',data);
	}

</script>

@endsection

resources/views/cms/roles/edit.blade.php
@extends('cms.parent')

@section('title','DEMO')
@section('page-large-name','Library System')
@section('page-small-name','Books')

@section('styles')

@endsection

@section('content')
    <!-- Main content -->
    <section class="content">
		<div class="container-fluid">
		  <div class="row">
			<!-- left column -->
			<div class="col-md-12">
			  <!-- general form elements -->
			  <div class="card card-primary">
				<div class="card-header">
				  <h3 class="card-title">Update Book</h3>
				</div>


			

				<!-- /.card-header -->
				<!-- form start -->
				<form method="POST" >
					@csrf
                  
					<!--we need to make it appear when their is an error  , $errors = we make validation auto request validator return array (errors)
					result of failer >> errors of validation rules  the next step we need to show the errors (li) >>loop >>
					value old >> return old data 
					-->
				      
				  <div class="card-body">
					<div class="form-group">

                     
					<div class="form-group">
					  <label for="name">Name</label>
					  <input type="text" class="form-control"  name="name" id="name" placeholder="Enter name">
					</div>

					<div class="form-group">
					  <label for="year">Year</label>
					  <input type="number" class="form-control"   id="year" placeholder="year">
					</div>

					<div class="form-group">
						<label>Language</label>
						<select class="form-control languages" id= "language" style="width: 100%;">
						  <option  value="en">English</option>
						  <option  value="ar">Arabic</option>
						  
						
						</select>
					  </div>


					  <div class="form-group">
						<label for="quantity">Quantity</label>
						<input type="number" class="form-control"   id="quantity" placeholder="quantity">
					  </div>
				
					<div class="form-group">
						<div class="custom-control custom-switch">
						  <input type="checkbox" class="custom-control-input" name="visible" id="visible" checked >
						  <label class="custom-control-label" for="visible">visible</label>
						</div>
					  </div>
				
				  </div>
				  <!-- /.card-body -->
  
				  <div class="card-footer">
					<button type="button" onclick="updateBook({{$book->id}})" class="btn btn-primary">Submit</button>
				  </div>

					  
				</form>
			  </div>
			  <!-- /.card -->
  
		
  
			</div>
			<!--/.col (left) -->
		
		  </div>
		  <!-- /.row -->
		</div><!-- /.container-fluid -->
	  </section>
	  <!-- /.content -->
@endsection
 

@section('scripts')


<script>
	   function updateBook(id){
				 let data ={
		        name :document.getElementById('name').value,
	        	 year :document.getElementById('year').value,
	        	 quantity :document.getElementById('quantity').value,
		       //  category_id :document.getElementById('category_id').value,
		 language :document.getElementById('language').value,
	        	 visible :document.getElementById('visible').checked,

				 }
				 update('/cms/admin/books/'+ id,data,'/cms/admin/books')
			 }
</script>
 

@endsection

resources/views/cms/roles/index.blade.php
@extends('cms.parent')

@section('title','Roles')
@section('page-large-name','Roles')
@section('page-small-name','Index-show')

@section('styles')

@endsection

@section('content')
    <!-- Main content -->
    <section class="content">
		<div class="container-fluid">
		  <div class="row">
			<div class="col-md-12">
			  <div class="card">
				<div class="card-header">
				  <h3 class="card-title">Bordered Table</h3>
				</div>
				<!-- /.card-header -->
				<div class="card-body">
				  <table class="table table-bordered table-striped table-hover">
					<thead>
					  <tr>
						<th style="width: 10px">#</th>
						<th>Name</th>
						<th>Guard</th>
						<th>Permissions</th>
						<th>Created At</th>
						<th>Updated At</th>
						<th>Settings</th>
					  </tr>
					</thead>
					<tbody>
						@foreach ($roles as $role)
						<tr>
							<td>{{$role->id}}</td>
							<td>{{$role->name}}</td>
						
							<td>
								<span class="badge bg-info">{{$role->guard_name}}</span>
							</td>
							<!--We need to send number of permissions-->
							<td>
								<a href="{{route('role.show',$role->id)}}" class="btn btn-block btn-warning btn-sm">
									({{$role->permissions_count}}) Permission/s
								</a>
							</td>
							<td>{{$role->created_at->format('y-m-d H:ma')}}</td>
							<td>{{$role->updated_at->format('y-m-d H:ma')}}</td>
							<td>
								<div class="btn-group">
										<!--Edit  Button-->
									<a href="{{route('roles.edit',$role->id)}}" class="btn btn-info">
									  <i class="fas fa-edit"></i>  
									</a>
	<!--Java Script way-->
									<a onclick="deleteRole({{$role->id}}, this )" class="btn btn-danger">
										<i class="fas fa-trash"></i>
									</a>
								
							
							
								  </div>
							</td>
							
						  </tr>
						@endforeach
						<!--For Knowledge-->
						{{--@if ($data->visible)
						<td>True</td>
					     @else
					     <td>False</td>
					     @endif--}}
					
					</tbody>
				  </table>
				</div>
				<!-- /.card-body -->
		
			  </div>
			  <!-- /.card -->
  
			
			</div>
			<!-- /.col -->
		  </div> 
		  <!-- /.row -->
		</div><!-- /.container-fluid -->
	  </section>
	  <!-- /.content -->
@endsection


@section('scripts')
 <script>
	 
	 function deleteRole(id ,ref){
		confirmDestroy('/cms/admin/roles',id ,ref)
	 }
	 </script>

@endsection

{{-- Swal.fire(
	'Deleted!',
	'Your file has been deleted.',
	'success'
  ) --}}

resources/views/cms/roles/role-permission.blade.php
@extends('cms.parent')

@section('title','Roles-Permissions')
@section('page-large-name','Roles-Permission')
@section('page-small-name','Index')

@section('styles')
<link rel="stylesheet" href="{{asset('cms/plugins/icheck-bootstrap/icheck-bootstrap.min.css')}}">
@endsection

@section('content')
    <!-- Main content -->
    <section class="content">
		<div class="container-fluid">
		  <div class="row">
			<div class="col-md-12">
			  <div class="card">
				<div class="card-header">
				  <h3 class="card-title">{{$role->name}} Permission </h3>
				</div>
				<!-- /.card-header -->
				<div class="card-body">
				  <table class="table table-bordered table-striped table-hover">
					<thead>
					  <tr>
						<th style="width: 10px">#</th>
						<th>Permission Name</th>
						<th>Permission Guard</th>
						<th>Assigned</th>
					  </tr>
					</thead>
					<tbody>
						@foreach ($permissions as $permission)
						<tr>
							<td>{{$permission->id}}</td>
							<td>{{$permission->name}}</td>
						
							<td>
								<!--We need to send number of permissions-->
								<span class="badge bg-info">{{$permission->guard_name}}</span>
							</td>	
							<td>
								
							<div class="icheck-success d-inline">
								<input type="checkbox" 
								 onclick="assinedPermission('{{$role->id}}','{{$permission->id}}')"
								@if($permission->assigned)
								checked 
								@endif
								id="permission_{{$permission->id}}">
								<label for="permission_{{$permission->id}}">
								</label>
							</div>
							</td>
							
						  </tr>
						@endforeach
						<!--For Knowledge-->
						{{--@if ($data->visible)
						<td>True</td>
					     @else
					     <td>False</td>
					     @endif--}}
					
					</tbody>
				  </table>
				</div>
				<!-- /.card-body -->
		
			  </div>
			  <!-- /.card -->
  
			
			</div>
			<!-- /.col -->
		  </div> 
		  <!-- /.row -->
		</div><!-- /.container-fluid -->
	  </section>
	  <!-- /.content -->
@endsection


@section('scripts')
 <script>
	 
	//we need to add permissions for role 
	//every check on permission will be add 
	function assinedPermission(roleId , permissionId){
	axios.post('/cms/admin/permissions/role' , {
		role_id :roleId,
		permission_id :permissionId
	})
	.then(function (response) {
	// handle success code 2xx
	console.log(response);
	toastr.success(response.data.message)
	})
	.catch(function (error) {
	// handle error 4xx 5xx
	console.log(error);
	toastr.error(error.response.data.message)
	});
	
	}
	 </script>

@endsection

{{-- Swal.fire(
	'Deleted!',
	'Your file has been deleted.',
	'success'
  ) --}}