routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\Authcontroller;
use App\Http\Controllers\BookController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CountryController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\RolePermissionController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\UserPermissionController;
use App\Http\Middleware\checkAge;
use App\Mail\WelComeEmail;
use App\Models\Category;
use GuzzleHttp\Middleware;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/* Route::get('/', function () {
    return view('welcome');
}); */
//admin + user (web) both > login + logout 
//admin >> categories + countries 
//user > books 
//we need to add guard as parameter , dynamic attribute 

Route::prefix('cms/')->middleware('guest:admin,user')->group(function(){
  //  Route::view('login','cms.auth.login')->name('cms.login');
  Route::get('{guard}/login',[Authcontroller::class,'showlogin'])->name('cms.login');
  Route::post('login',[Authcontroller::class,'login']);
});

Route::prefix('cms/admin')->middleware('auth:admin')->group(function (){
  /*Note: route resbonsible to show >> index */
  Route::resource('admins', AdminController::class);
  Route::resource('roles', RoleController::class);
  Route::resource('permissions', PermissionController::class);
  
  Route::resource('permissions/role', RolePermissionController::class);
  Route::resource('permissions/user-permissions', UserPermissionController::class);
  Route::resource('users', UserController::class);
  

});

Route::prefix('cms/admin')->middleware('auth:admin,user')->group(function () {
  Route::view('/', 'cms.empty');
  Route::resource('books', BookController::class);
  Route::resource('categories', CategoryController::class);
  Route::resource('countries', CountryController::class);
  Route::get('change-password', [Authcontroller::class, 'showChangePassword'])->name('cms.changePassword');
  Route::post('change-password', [Authcontroller::class, 'changePassword']);
  Route::get('logout', [Authcontroller::class, 'logout'])->name('cms.logout');
});


Route::prefix('mail')->group(function(){
      Route::get('welcome',function(){
        return new WelComeEmail(); //markdown blade 
      });
});




//First way >> installation method of middleware 
// Route::get('news',function(){
//    return 'welcome to news page ';
// })->middleware('age:22',);


//second way 
// Route::get('news',function(){
  
//   /// return 'welcome to news page ';
//    return response()->json(['status'=>'success','active'=>true]);
//  })->middleware(checkAge::class);

 //third way 
//  Route::middleware('age:22',)->get('news',function(){
//     return 'welcome to news page ';
//  });

//forth way 
// Route::middleware('age:22',)->group(function(){
//   Route::get('news',function(){
//    return 'welcome to news page';
//      })->withoutMiddleware('age');
// });

app/Models/Book.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Book extends Model
{
    use HasFactory , SoftDeletes;  //first add trate , then we add a new col in creatte table migration >>Deleted At 
    //we have five process > Trashed , withtrash , onlytrash , forcedelete , restore
    //السوفت ديليت تحويل النل الى قيمة
    public function getVisibilityStatusAttribute()
    {
        return $this->is_visible ? 'visible' : 'Hidden';
    }

    
    public function getlanguageNameAttribute(){
        return $this->language == 'en' ? 'English' : 'Arabic';
    }

    public function category(){

        return $this->belongsTo(Category::class,'category_id','id');

    }
}

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    //add attribute in show stage only 
    //add object to the table that not appear to the user 

    protected $appends =['visibility_status']; 

    //get attribute without appends does not add the new attribute to the model 
    //how model deal with boolean ? visible is array in the laravel system
    //so when we use it we call something in the system >> rreserved keyword
    //we should change the name of the colum in the table
    public function getVisibilityStatusAttribute(){
        return $this->is_visible ? 'visible' : 'Hidden' ;
    }


    //Relation 
    public function books(){
        return $this->hasMany(Book::class,'category_id','id');
    }
}

app/Http/Controllers/API/CategoryController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{

    //1- resourse controller +2- model binding  + 3-model name 

    //each rout talks with func contorller >> policy function according type 
    //every function in controller >> policy function 
    //we can apply authorize resourse at once or write i at each function
    //Note : name of ability >> name of policy function
    public function __construct()
    {
        $this->authorizeResource(Category::class, 'category'); //make connect between controller and policy 
        //يعمم على الجميع بشرط يكون الكونترولر ريسورس مودل باينديغ 
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // test
/*         echo "we are in index "; */
         //QUERY ELOQUNT TO RETURN DATA 
        // $data=Category::all(); //if we need where >>get
        $data = Category::withCount('books')->get(); 
         return response()->view('cms.categories.index',['categories'=>$data]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
      //  $this->authorize('create', Category::class); //we should write it in each func when the attribute is binding
        return response()->view('cms.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //form button submit >> every input >> value to store method post
        //dd($request->all());
        //we have sth called page Expired >>419 (الحماية من عمليات الاستخدام غير الامنة ) 	@csrf Token 
        //we have to make validation  on data 
      //  $this->authorize('create', Category::class);
         $request->validate([
             'name'=>'required|string|min:3|max:20',
             'description'=>'nullable|string|min:3|max:50',
             'visible'=>'in:on|string'     //when we click submit there is sth say like return , but befor appear debug error 
         ],[
                 'name.required'=>'Please enter name !'

         ]);
         
        $category = new Category();
        $category->name =$request->get('name');
        $category->description =$request->get('Description');
        $category->is_visible=$request->has('visible');
        $isSaved=$category->save();
        if($isSaved){
         //   return redirect()->route('categories.index');
         session()->flash('type','success');
         session()->flash('message','category saved successfully'); //quick message read then disapeard 

            return redirect()->back();   
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
       
        //$this ->authorize('view',[$category]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

         $category = Category::find($id);
        $this->authorize('update',[Category::find($id)]);
        // we send parameter >find or fail > model binding 
        return response()->view('cms.categories.edit',['category'=>$category]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        //
        $request-> validate([
            'name'=>'required|string|min:3|max:20',
            'description'=>'nullable|string|min:3|max:50',
            'visible'=>'in:on|string' 

        ]);
    $category->name=$request->get('name');
    $category->description=$request->get('description');
    $category->is_visible=$request->has('visible');
    $isSaved =$category->save();
    if($isSaved){
        return redirect()->route('categories.index');

    }else{
        session()->flash('message','updated failed !');
        session()->flash('type','danger');
        return redirect()->back();
    }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        //primary key > id we didn't change it 
        $deleted= $category->delete();
        if($deleted){
             return response()->json(['title'=>'Deleted successfully','icon'=>'success']); //key>>string""  value>>int object double boolean array of any type or array of json  //begin with objects or array
        }else{
            return response()->json(['title'=>'Deleted failed','icon'=>'danger']);
        }
    //     if($deleted)
    //     return redirect()->back();
    // }
}
}

resources/views/cms/categories/create.blade.php
@extends('cms.parent')

@section('title','DEMO')
@section('page-large-name','Library System')
@section('page-small-name','categories')

@section('styles')

@endsection

@section('content')
    <!-- Main content -->
    <section class="content">
		<div class="container-fluid">
		  <div class="row">
			<!-- left column -->
			<div class="col-md-12">
			  <!-- general form elements -->
			  <div class="card card-primary">
				<div class="card-header">
				  <h3 class="card-title">Create Category</h3>
				</div>


			

				<!-- /.card-header -->
				<!-- form start -->
				<form method="POST" action="{{route('categories.store')}}" >
					@csrf

					<!--we need to make it appear when their is an error  , $errors = we make validation auto request validator return array (errors)
					result of failer >> errors of validation rules  the next step we need to show the errors (li) >>loop >>
					value old >> return old data 
					-->
				      
				  <div class="card-body">
					@if ($errors->any())
					<div class="alert alert-danger alert-dismissible">
					   <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
					   <h5><i class="icon fas fa-ban"></i> Alert!</h5>
					   @foreach ($errors->all() as $error)
							 <li>{{$error}}</li>
					   @endforeach
				   
					 </div>
					 
					 @endif
					 @if (session()->has('message')) 
					 <div class="alert alert-{{session()->get('type')}} alert-dismissible">
					   <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
					   <h5><i class="icon fas fa-check"></i> Success !</h5>
								{{session()->get('message')}}
					 </div>
					 @endif
					<div class="form-group">
					  <label for="name">Name</label>
					  <input type="text" class="form-control" value="{{old('name')}}"  name="name" id="name" placeholder="Enter name">
					</div>
					<div class="form-group">
					  <label for="Description">Description</label>
					  <input type="text" class="form-control"   value="{{old('Description')}}" name="Description" id="Description" placeholder="Description">
					</div>
				
					<div class="form-group">
						<div class="custom-control custom-switch">
						  <input type="checkbox" class="custom-control-input" name="visible" id="visible" checked >
						  <label class="custom-control-label" for="visible">visible</label>
						</div>
					  </div>
				
				  </div>
				  <!-- /.card-body -->
  
				  <div class="card-footer">
					<button type="submit" class="btn btn-primary">Submit</button>
				  </div>
				</form>
			  </div>
			  <!-- /.card -->
  
		
  
			</div>
			<!--/.col (left) -->
		
		  </div>
		  <!-- /.row -->
		</div><!-- /.container-fluid -->
	  </section>
	  <!-- /.content -->
@endsection
 

@section('scripts')
@endsection

resources/views/cms/categories/edit.blade.php
@extends('cms.parent')

@section('title','DEMO')
@section('page-large-name','Library System')
@section('page-small-name','categories')

@section('styles')

@endsection

@section('content')
    <!-- Main content -->
    <section class="content">
		<div class="container-fluid">
		  <div class="row">
			<!-- left column -->
			<div class="col-md-12">
			  <!-- general form elements -->
			  <div class="card card-primary">
				<div class="card-header">
				  <h3 class="card-title">update Category</h3>
				</div>


			

				<!-- /.card-header -->
				<!-- form start -->
				<form method="POST" action="{{route('categories.update',$category->id)}}" >
					@csrf
                     @method('PUT')
					<!--we need to make it appear when their is an error  , $errors = we make validation auto request validator return array (errors)
					result of failer >> errors of validation rules  the next step we need to show the errors (li) >>loop >>
					value old >> return old data 
					-->
				      
				  <div class="card-body">
					@if ($errors->any())
					<div class="alert alert-danger alert-dismissible">
					   <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
					   <h5><i class="icon fas fa-ban"></i> Alert!</h5>
					   @foreach ($errors->all() as $error)
							 <li>{{$error}}</li>
					   @endforeach
				   
					 </div>
					 
					 @endif
					 @if (session()->has('message')) 
					 <div class="alert alert-success alert-dismissible">
					   <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
					   <h5><i class="icon fas fa-check"></i> Success !</h5>
								{{session()->get('message')}}
					 </div>
					 @endif
					<div class="form-group">
					  <label for="name">Name</label>
					  <input type="text" class="form-control"  @if(old('name')) value="{{old('name')}}" @else value="{{$category->name}}" @endif name="name" id="name" placeholder="Enter name">
					</div>
					<div class="form-group">
					  <label for="Description">Description</label>
					  <input type="text" class="form-control"  @if(old('Description')) value="{{old('Description')}}" @else value="{{$category->description}}" @endif  name="Description" id="Description" placeholder="Description">
					</div>
				
					<div class="form-group">
						<div class="custom-control custom-switch">
						  <input type="checkbox" class="custom-control-input" name="visible" id="visible"  @if($category->is_visible) checked @endif>
						 
						  <label class="custom-control-label" for="visible">visible</label>
						</div>
					  </div>
				
				  </div>
				  <!-- /.card-body -->
  
				  <div class="card-footer">
					<button type="submit" class="btn btn-primary">Submit</button>
				  </div>
				</form>
			  </div>
			  <!-- /.card -->
  
		
  
			</div>
			<!--/.col (left) -->
		
		  </div>
		  <!-- /.row -->
		</div><!-- /.container-fluid -->
	  </section>
	  <!-- /.content -->
@endsection
 

@section('scripts')
@endsection

resources/views/cms/categories/index.blade.php
@extends('cms.parent')

@section('title','Categories')
@section('page-large-name','Categories')
@section('page-small-name','Index-show')

@section('styles')

@endsection

@section('content')
    <!-- Main content -->
    <section class="content">
		<div class="container-fluid">
		  <div class="row">
			<div class="col-md-12">
			  <div class="card">
				<div class="card-header">
				  <h3 class="card-title">Bordered Table</h3>
				</div>
				<!-- /.card-header -->
				<div class="card-body">
				  <table class="table table-bordered table-striped table-hover">
					<thead>
					  <tr>
						<th style="width: 10px">#</th>
						<th>Name</th>
						<th>Books</th>
						<th>Visible</th>
						<th>Created At</th>
						<th>Updated At</th>
						<th>Settings</th>
					  </tr>
					</thead>
					<tbody>
						@foreach ($categories as $data)
						<tr>
							<td>{{$data->id}}</td>
							<td>{{$data->name}}</td>
							<td>
								<span class="badge bg-info">({{$data->books_count}}) Book/s</span>
							</td>
							

							
							<td>
								<span class="badge @if ($data->is_visible) bg-success
									
								@else  bg-danger @endif">	{{$data->visibility_status}}</span>
							</td>
							<td>{{$data->created_at->format('y-m-d H:ma')}}</td>
							<td>{{$data->updated_at->format('y-m-d H:ma')}}</td>
							<td>
								<div class="btn-group">
										<!--Edit  Button-->
									<a href="{{route('categories.edit',$data->id)}}" class="btn btn-info">
									  <i class="fas fa-edit"></i>  
									</a>
	<!--Java Script way-->
									<a onclick="deleteCountry({{$data->id}}, this )" class="btn btn-danger">
										<i class="fas fa-trash"></i>
									</a>
									<!--WE Can't sent a check request  without using Form , if we sent the method as get then will be cause a conflict 
									because their is the same route as the delete (show)   so we put the type post to avoid conflict and gose direct to delete 
								-->
								<!--Delete Button traditional way-->

									{{-- <form method="POST" action="{{route('categories.destroy',$data->id)}}"> 
										@csrf 
										@method('DELETE')
									<button type="submit" class="btn btn-danger">
									  <i class="fas fa-trash"></i>
									</button>
								</form> --}}
							
							
								  </div>
							</td>
							
						  </tr>
						@endforeach
						<!--For Knowledge-->
						{{--@if ($data->visible)
						<td>True</td>
					     @else
					     <td>False</td>
					     @endif--}}
					
					</tbody>
				  </table>
				</div>
				<!-- /.card-body -->
		
			  </div>
			  <!-- /.card -->
  
			
			</div>
			<!-- /.col -->
		  </div> 
		  <!-- /.row -->
		</div><!-- /.container-fluid -->
	  </section>
	  <!-- /.content -->
@endsection


@section('scripts')
 <script>
	 

	 function deleteCountry(id ,ref){
		confirmDestroy('/cms/admin/categories',id ,ref)
	 }
	 </script>


@endsection

{{-- Swal.fire(
	'Deleted!',
	'Your file has been deleted.',
	'success'
  ) --}}